import { Badge, Quest, Task, UserProfile } from '../models/types';

export const INITIAL_USER: UserProfile = {
  id: 'usr_quest_101',
  name: 'Aria Vance',
  email: 'aria.vance@focusquest.ai',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
  level: 4,
  xp: 340,
  xpToNextLevel: 500,
  streak: 5,
  lastActiveDate: new Date().toISOString().split('T')[0],
  totalFocusMinutes: 185,
  tasksCompletedCount: 14,
  unlockedBadges: ['badge_first_quest', 'badge_streak_3', 'badge_focus_1hr'],
  preferences: {
    theme: 'dark',
    highContrast: false,
    soundEnabled: true,
    autoStartBreaks: false,
  },
};

export const ALL_BADGES: Badge[] = [
  {
    id: 'badge_first_quest',
    name: 'Novice Adventurer',
    description: 'Complete your very first task on FocusQuest',
    iconName: 'Sparkles',
    category: 'Tasks',
  },
  {
    id: 'badge_streak_3',
    name: 'Ignited Flame',
    description: 'Maintain a 3-day active daily streak',
    iconName: 'Flame',
    category: 'Streak',
  },
  {
    id: 'badge_streak_7',
    name: 'Unstoppable Momentum',
    description: 'Achieve a 7-day streak',
    iconName: 'Zap',
    category: 'Streak',
  },
  {
    id: 'badge_focus_1hr',
    name: 'Deep Worker',
    description: 'Accumulate over 60 minutes of uninterrupted focus time',
    iconName: 'Clock',
    category: 'Focus',
  },
  {
    id: 'badge_focus_5hr',
    name: 'Zen Master',
    description: 'Accumulate over 300 minutes of focus time',
    iconName: 'BrainCircuit',
    category: 'Focus',
  },
  {
    id: 'badge_ai_strategist',
    name: 'AI Architect',
    description: 'Generate an AI study or work plan',
    iconName: 'Bot',
    category: 'AI',
  },
  {
    id: 'badge_task_master_10',
    name: 'Quest Conqueror',
    description: 'Complete 10 high priority tasks',
    iconName: 'Trophy',
    category: 'Tasks',
  },
];

export const INITIAL_QUESTS: Quest[] = [
  {
    id: 'q_daily_3',
    title: 'Daily Conqueror',
    description: 'Complete 3 tasks today',
    xpReward: 50,
    targetCount: 3,
    currentCount: 1,
    completed: false,
    type: 'daily_tasks',
  },
  {
    id: 'q_focus_25',
    title: 'Deep Focus Sprint',
    description: 'Log 25 minutes of Pomodoro focus time',
    xpReward: 40,
    targetCount: 25,
    currentCount: 15,
    completed: false,
    type: 'focus_time',
  },
  {
    id: 'q_ai_plan',
    title: 'Strategic Planner',
    description: 'Generate an AI schedule in the AI Planner',
    xpReward: 30,
    targetCount: 1,
    currentCount: 0,
    completed: false,
    type: 'ai_planner',
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task_1',
    userId: 'usr_quest_101',
    title: 'Design System Architecture Review',
    description: 'Examine components, color tokens, and accessibility standards for the new portal release.',
    deadline: new Date(Date.now() + 86400000 * 1).toISOString().split('T')[0],
    priority: 'High',
    completed: false,
    tags: ['Design', 'Work'],
    estimatedMinutes: 45,
    subtasks: [
      { id: 'sub_1_1', title: 'Audit color contrast ratios', completed: true },
      { id: 'sub_1_2', title: 'Export Figma UI Kit variables', completed: false },
      { id: 'sub_1_3', title: 'Draft accessibility checklist', completed: false },
    ],
    xpReward: 40,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'task_2',
    userId: 'usr_quest_101',
    title: 'AI Planner Module Testing',
    description: 'Test prompt variations for Gemini API task breakdown and verify JSON response schema.',
    deadline: new Date(Date.now() + 86400000 * 2).toISOString().split('T')[0],
    priority: 'High',
    completed: false,
    tags: ['AI', 'Engineering'],
    estimatedMinutes: 30,
    subtasks: [
      { id: 'sub_2_1', title: 'Verify Gemini 3.6 Flash fallback', completed: true },
      { id: 'sub_2_2', title: 'Benchmark response latency', completed: false },
    ],
    xpReward: 35,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'task_3',
    userId: 'usr_quest_101',
    title: '30-Min Cardio & Core Workout',
    description: 'Keep up physical momentum for health quest bonus XP.',
    deadline: new Date().toISOString().split('T')[0],
    priority: 'Medium',
    completed: true,
    completedAt: new Date().toISOString(),
    tags: ['Health', 'Habit'],
    estimatedMinutes: 30,
    subtasks: [
      { id: 'sub_3_1', title: '15 min treadmill run', completed: true },
      { id: 'sub_3_2', title: 'Core stability routine', completed: true },
    ],
    xpReward: 25,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'task_4',
    userId: 'usr_quest_101',
    title: 'Weekly Budget & Expenses Sync',
    description: 'Review subscription services and update financial spreadsheet.',
    deadline: new Date(Date.now() + 86400000 * 4).toISOString().split('T')[0],
    priority: 'Low',
    completed: false,
    tags: ['Personal', 'Finance'],
    estimatedMinutes: 20,
    subtasks: [],
    xpReward: 20,
    createdAt: new Date().toISOString(),
  },
];
